name: Download releases and upload to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # timezone: UTC
    # 避開整點時間，因為有可能會有時間上的延誤
    - cron: '40 16 * * *'

permissions:
  actions: write # liskin/gh-workflow-keepalive@v1
  contents: read
  id-token: write
  pages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: install and build
        run: |
          set -ex
          yarn
          yarn tsx index.ts
      - uses: actions/configure-pages@v4
        if: github.ref == 'refs/heads/master'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v4
      - uses: liskin/gh-workflow-keepalive@v1